theme: jekyll-theme-cayman
title: Fix Sitting Posture 
show_downloads: true
is_project_page: true
description: Fix your computer sitting posture! <img src="https://media.giphy.com/media/WUlplcMpOCEmTGBtBW/giphy.gif" width="30"> 
